export const advertises = [
  {
    id: "1",
    location: "ایران، مازندران",
    rate: "4.9",
    pricePerNight: "450",
    hostedBy: "مهرداد و سارا",
    images: [
      { src: "/images/homes/home-1-1.jpg", alt: "" },
      { src: "/images/homes/home-1-2.jpg", alt: "" },
      { src: "/images/homes/home-1-3.jpg", alt: "" },
      { src: "/images/homes/home-1-4.jpg", alt: "" },
      { src: "/images/homes/home-1-5.jpg", alt: "" },
    ],
  },
  {
    id: "2",
    location: "ایران، مازندران",
    rate: "4.7",
    pricePerNight: "800",
    hostedBy: "علی",
    images: [
      { src: "/images/homes/home-2-1.jpg", alt: "" },
      { src: "/images/homes/home-2-2.jpg", alt: "" },
      { src: "/images/homes/home-2-3.jpg", alt: "" },
      { src: "/images/homes/home-2-4.jpg", alt: "" },
      { src: "/images/homes/home-2-5.jpg", alt: "" },
      { src: "/images/homes/home-2-6.jpg", alt: "" },
      { src: "/images/homes/home-2-7.jpg", alt: "" },
      { src: "/images/homes/home-2-8.jpg", alt: "" },
    ],
  },
  {
    id: "3",
    location: "ایران، مازندران",
    rate: "4.8",
    pricePerNight: "780",
    hostedBy: "مریم",
    images: [
      { src: "/images/homes/home-3-1.jpg", alt: "" },
      { src: "/images/homes/home-3-2.jpg", alt: "" },
      { src: "/images/homes/home-3-3.jpg", alt: "" },
      { src: "/images/homes/home-3-4.jpg", alt: "" },
      { src: "/images/homes/home-3-5.jpg", alt: "" },
      { src: "/images/homes/home-3-6.jpg", alt: "" },
      { src: "/images/homes/home-3-7.jpg", alt: "" },
      { src: "/images/homes/home-3-8.jpg", alt: "" },
      { src: "/images/homes/home-3-9.jpg", alt: "" },
    ],
  },
  {
    id: "4",
    location: "ایران، مازندران",
    rate: "4.6",
    pricePerNight: "430",
    hostedBy: "پارسا و ترانه",
    images: [
      { src: "/images/homes/home-4-1.jpg", alt: "" },
      { src: "/images/homes/home-4-2.jpg", alt: "" },
      { src: "/images/homes/home-4-3.jpg", alt: "" },
      { src: "/images/homes/home-4-4.jpg", alt: "" },
      { src: "/images/homes/home-4-5.jpg", alt: "" },
      { src: "/images/homes/home-4-6.jpg", alt: "" },
      { src: "/images/homes/home-4-7.jpg", alt: "" },
      { src: "/images/homes/home-4-8.jpg", alt: "" },
    ],
  },
  {
    id: "5",
    location: "ایران، مازندران",
    rate: "4.2",
    pricePerNight: "930",
    hostedBy: "بیژن",
    images: [
      { src: "/images/homes/home-5-1.jpg", alt: "" },
      { src: "/images/homes/home-5-2.jpg", alt: "" },
      { src: "/images/homes/home-5-3.jpg", alt: "" },
      { src: "/images/homes/home-5-4.jpg", alt: "" },
      { src: "/images/homes/home-5-5.jpg", alt: "" },
      { src: "/images/homes/home-5-6.jpg", alt: "" },
      { src: "/images/homes/home-5-7.jpg", alt: "" },
      { src: "/images/homes/home-5-8.jpg", alt: "" },
      { src: "/images/homes/home-5-9.jpg", alt: "" },
    ],
  },
  {
    id: "6",
    location: "ایران، مازندران",
    rate: "4.1",
    pricePerNight: "890",
    hostedBy: "پگاه",
    images: [
      { src: "/images/homes/home-6-1.jpg", alt: "" },
      { src: "/images/homes/home-6-2.jpg", alt: "" },
      { src: "/images/homes/home-6-3.jpg", alt: "" },
      { src: "/images/homes/home-6-4.jpg", alt: "" },
      { src: "/images/homes/home-6-5.jpg", alt: "" },
      { src: "/images/homes/home-6-6.jpg", alt: "" },
      { src: "/images/homes/home-6-7.jpg", alt: "" },
    ],
  },
];
